import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8081/');
  await page.getByRole('button', { name: 'Mon compte' }).click();
  await page.getByRole('link', { name: 'Créer un compte' }).click();
  await page.getByPlaceholder('Nom', { exact: true }).click();
  await page.getByPlaceholder('Nom', { exact: true }).press('CapsLock');
  await page.getByPlaceholder('Nom', { exact: true }).fill('T');
  await page.getByPlaceholder('Nom', { exact: true }).press('CapsLock');
  await page.getByPlaceholder('Nom', { exact: true }).fill('Test1');
  await page.getByPlaceholder('Nom', { exact: true }).press('Tab');
  await page.getByPlaceholder('Prénom').press('CapsLock');
  await page.getByPlaceholder('Prénom').fill('T');
  await page.getByPlaceholder('Prénom').press('CapsLock');
  await page.getByPlaceholder('Prénom').fill('Test2');
  await page.getByPlaceholder('Prénom').press('Tab');
  await page.getByPlaceholder('email@domain.com').fill('test@test');
  await page.getByPlaceholder('email@domain.com').press('CapsLock');
  await page.getByPlaceholder('email@domain.com').fill('test@test.');
  await page.getByPlaceholder('email@domain.com').press('CapsLock');
  await page.getByPlaceholder('email@domain.com').fill('test@test.com');
  await page.getByPlaceholder('email@domain.com').press('Control+ArrowLeft');
  await page.getByPlaceholder('email@domain.com').press('Control+ArrowLeft');
  await page.getByPlaceholder('email@domain.com').press('Control+ArrowLeft');
  await page.getByPlaceholder('email@domain.com').press('Control+ArrowLeft');
  await page.getByPlaceholder('email@domain.com').fill('testplaywright@test.com');
  await page.getByPlaceholder('email@domain.com').press('ArrowUp');
  await page.getByPlaceholder('email@domain.com').press('ArrowUp');
  await page.getByPlaceholder('Prénom').click();
  await page.getByPlaceholder('Prénom').click();
  await page.getByPlaceholder('Prénom').fill('');
  await page.getByPlaceholder('Prénom').press('CapsLock');
  await page.getByPlaceholder('Prénom').fill('P');
  await page.getByPlaceholder('Prénom').press('CapsLock');
  await page.getByPlaceholder('Prénom').fill('Playwright');
  await page.getByPlaceholder('Mot de passe', { exact: true }).click();
  await page.getByPlaceholder('Mot de passe', { exact: true }).press('CapsLock');
  await page.getByPlaceholder('Mot de passe', { exact: true }).fill('P');
  await page.getByPlaceholder('Mot de passe', { exact: true }).press('CapsLock');
  await page.getByPlaceholder('Mot de passe', { exact: true }).fill('Password@1234');
  await page.getByPlaceholder('Mot de passe', { exact: true }).press('Tab');
  await page.getByPlaceholder('Confirmation Mot de Passe').press('CapsLock');
  await page.getByPlaceholder('Confirmation Mot de Passe').fill('P');
  await page.getByPlaceholder('Confirmation Mot de Passe').press('CapsLock');
  await page.getByPlaceholder('Confirmation Mot de Passe').fill('Password@1234');
  await page.getByRole('button', { name: 'Créer mon compte' }).click();
});
